rtabmap:
  ros__parameters:
    subscribe_rgbd: true
    frame_id: "camera_color_optical_frame"
    Rtabmap/DetectionRate: "10.0"
    RGBD/MinDepth: "0.2"
    RGBD/MaxDepth: "20.0"
    RGBD/NeighborLinkRefining: "true"

